library(shiny)
library(shinyjs)
library(plotly)
library(GenomicRanges)
library(magrittr)

load("data/encode_preload.RData")
load("data/codex_preload.RData")
load("data/codex_human_chip_preload.RData")
load("data/modEncodeD_ChIPseq_preload.RData")